version: "3"
services:
  nifi_mysql:
    container_name: nifi_mysql
    image: docker.io/bitnami/mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/bitnami/mysql/data"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=future_nations
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mysql/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6
  nifi:
    image: apache/nifi:latest
    depends_on:
      - nifi_mysql
    ports:
      - "8443:8443"
    volumes:
      - ./mysql-connector-j-8.1.0:/mysql/drivers/mysql-connector
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    restart: always

volumes:
  mysql_data:
    driver: local
